export type Entry = {
  id: string;
  front: string;
  back: string;
  roman: string;
  note: string;
  speak: string;
  lessonId: string;
};
export type Lesson = {
  id: string;
  title: string;
  subtitle: string;
  text: string;
  check: {
    question: string;
    options: string[];
    answer: number;
    explanation: string;
  };
};
export const lessons: Lesson[] = [
  {
    id: "vowels",
    title: "Your first six vowels",
    subtitle: "Start with the sounds",
    text: "Hangul is the Korean alphabet. Letters fit together into syllable blocks. Begin with six vowels: ㅏ ㅓ ㅗ ㅜ ㅡ ㅣ. Listen to each example. A vowel needs a silent ㅇ before it to make a written syllable: ㅏ becomes 아. English sound comparisons and romanization are only approximations.",
    check: {
      question: "Which syllable contains ㅏ?",
      options: ["아", "오", "우"],
      answer: 0,
      explanation: "아 is silent ㅇ plus the vowel ㅏ.",
    },
  },
  {
    id: "y-vowels",
    title: "Add a little “y”",
    subtitle: "Four more basic vowels",
    text: "An extra short stroke turns ㅏ, ㅓ, ㅗ, ㅜ into ㅑ, ㅕ, ㅛ, ㅠ. These begin with a y-like glide: ya, yeo, yo, yu. The spellings eo and eu each represent one vowel sound, not two separate English vowels.",
    check: {
      question: "Which vowel is written “yu”?",
      options: ["ㅛ", "ㅠ", "ㅑ"],
      answer: 1,
      explanation: "ㅠ is yu. Compare 우 (u) and 유 (yu).",
    },
  },
  {
    id: "consonants",
    title: "Meet the consonants",
    subtitle: "Seven building blocks",
    text: "Start with ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅅ. Their sounds depend on position; English letters are rough guides. ㄹ is a quick tongue tap between vowels and an l-like sound at the end of a syllable. Audio here uses a consonant with ㅏ, not the letter’s name.",
    check: {
      question: "Which letter makes an m sound?",
      options: ["ㄴ", "ㅁ", "ㅅ"],
      answer: 1,
      explanation: "ㅁ makes an m sound, as in 마.",
    },
  },
  {
    id: "more-consonants",
    title: "Air and silence",
    subtitle: "The other seven basic consonants",
    text: "ㅇ is silent at the start of a syllable, but sounds like ng at the end. ㅈ is a j-like sound. ㅊ ㅋ ㅌ ㅍ have a stronger puff of air than ㅈ ㄱ ㄷ ㅂ. ㅎ is h-like. Tense consonants and additional vowel combinations will come in a future course expansion.",
    check: {
      question: "What does ㅇ do at the start of 아?",
      options: ["Makes ng", "Is silent", "Makes h"],
      answer: 1,
      explanation: "Initial ㅇ is a silent placeholder. Final ㅇ makes ng.",
    },
  },
  {
    id: "blocks",
    title: "Build your first syllables",
    subtitle: "Letters become readable blocks",
    text: "Read a block from its initial consonant to its vowel, then any final consonant. Vertical vowels sit to the right: ㄴ + ㅏ = 나. Horizontal vowels sit below: ㅁ + ㅜ = 무. A final consonant sits underneath: ㅁ + ㅜ + ㄹ = 물. This final position is called batchim (받침).",
    check: {
      question: "What do ㅁ + ㅜ + ㄹ make?",
      options: ["무", "물", "나"],
      answer: 1,
      explanation: "물 has initial ㅁ, vowel ㅜ, and final ㄹ.",
    },
  },
  {
    id: "words",
    title: "Words you can read",
    subtitle: "Everyday words and useful phrases",
    text: "Read one syllable block at a time, then join the sounds. 나무 has two blocks: 나 + 무. 우유 has two silent initial ㅇ letters. Try saying each word before revealing its meaning. Start with the simple words, then try the school and club phrases. Later entries introduce additional vowel combinations, tense consonants, and pronunciation changes. Use the audio for guidance. The conversational phrases are polite; formality and context notes appear with their meanings.",
    check: {
      question: "What does 나무 mean?",
      options: ["Milk", "Tree", "Sea"],
      answer: 1,
      explanation: "나무 means tree. 우유 means milk; 바다 means sea.",
    },
  },
];
// Append new entries to each list. Positions form persistent card IDs; do not
// reorder or remove existing entries without an explicit ID migration.
const groups: Record<string, string[][]> = {
  vowels: [
    ["ㅏ", "a · open “ah” sound", "a", "아"],
    ["ㅓ", "eo · open, unrounded vowel", "eo", "어"],
    ["ㅗ", "o · rounded lips", "o", "오"],
    ["ㅜ", "u · rounded “oo” sound", "u", "우"],
    ["ㅡ", "eu · unrounded lips, tongue high and back", "eu", "으"],
    ["ㅣ", "i · “ee” sound", "i", "이"],
  ],
  "y-vowels": [
    ["ㅑ", "ya · y glide + ㅏ", "ya", "야"],
    ["ㅕ", "yeo · y glide + ㅓ", "yeo", "여"],
    ["ㅛ", "yo · y glide + ㅗ", "yo", "요"],
    ["ㅠ", "yu · y glide + ㅜ", "yu", "유"],
  ],
  consonants: [
    ["ㄱ", "g/k-like sound", "g/k", "가"],
    ["ㄴ", "n sound", "n", "나"],
    ["ㄷ", "d/t-like sound", "d/t", "다"],
    ["ㄹ", "r/l-like sound, depending on position", "r/l", "라"],
    ["ㅁ", "m sound", "m", "마"],
    ["ㅂ", "b/p-like sound", "b/p", "바"],
    ["ㅅ", "s sound; sh-like before ㅣ", "s", "사"],
  ],
  "more-consonants": [
    ["ㅇ", "Silent initially; ng at the end", "— / ng", "아"],
    ["ㅈ", "j-like sound", "j", "자"],
    ["ㅊ", "ch-like sound with a puff of air", "ch", "차"],
    ["ㅋ", "k sound with a puff of air", "k", "카"],
    ["ㅌ", "t sound with a puff of air", "t", "타"],
    ["ㅍ", "p sound with a puff of air", "p", "파"],
    ["ㅎ", "h-like sound", "h", "하"],
  ],
  blocks: [
    ["나", "ㄴ + ㅏ → 나", "na", "나"],
    ["무", "ㅁ + ㅜ → 무", "mu", "무"],
    ["물", "ㅁ + ㅜ + ㄹ → 물", "mul", "물"],
    ["강", "ㄱ + ㅏ + ㅇ → 강", "gang", "강"],
  ],
  words: [
    ["나무", "Tree", "namu", "나무"],
    ["바다", "Sea", "bada", "바다"],
    ["우유", "Milk", "uyu", "우유"],
    ["오이", "Cucumber", "oi", "오이"],
    ["아이", "Child", "ai", "아이"],
    ["나비", "Butterfly", "nabi", "나비"],
    ["물", "Water", "mul", "물"],
    ["하루", "A day", "haru", "하루"],
    ["가구", "Furniture", "gagu", "가구"],
    ["가수", "Singer", "gasu", "가수"],
    ["가시", "Thorn", "gasi", "가시"],
    ["가지", "Eggplant", "gaji", "가지"],
    ["구두", "Dress shoes", "gudu", "구두"],
    ["구름", "Cloud", "gureum", "구름"],
    ["고기", "Meat", "gogi", "고기"],
    ["고구마", "Sweet potato", "goguma", "고구마"],
    ["고추", "Chili pepper", "gochu", "고추"],
    ["국수", "Noodles", "guksu", "국수"],
    ["기차", "Train", "gicha", "기차"],
    ["나라", "Country", "nara", "나라"],
    ["다리", "Leg; bridge", "dari", "다리"],
    ["도시", "City", "dosi", "도시"],
    ["도로", "Road", "doro", "도로"],
    ["모자", "Hat", "moja", "모자"],
    ["머리", "Head; hair", "meori", "머리"],
    ["바지", "Pants", "baji", "바지"],
    ["버스", "Bus", "beoseu", "버스"],
    ["비누", "Soap", "binu", "비누"],
    ["사자", "Lion", "saja", "사자"],
    ["소리", "Sound", "sori", "소리"],
    ["수박", "Watermelon", "subak", "수박"],
    ["아기", "Baby", "agi", "아기"],
    ["아버지", "Father", "abeoji", "아버지"],
    ["어머니", "Mother", "eomeoni", "어머니"],
    ["오리", "Duck", "ori", "오리"],
    ["요리", "Cooking; a dish", "yori", "요리"],
    ["우산", "Umbrella", "usan", "우산"],
    ["지구", "Earth", "jigu", "지구"],
    ["지도", "Map", "jido", "지도"],
    ["치마", "Skirt", "chima", "치마"],
    ["코", "Nose", "ko", "코"],
    ["피", "Blood", "pi", "피"],
    ["포도", "Grapes", "podo", "포도"],
    ["하마", "Hippopotamus", "hama", "하마"],
    ["허리", "Waist; lower back", "heori", "허리"],
    ["호수", "Lake", "hosu", "호수"],
    ["호랑이", "Tiger", "horangi", "호랑이"],
    ["휴지", "Tissue; toilet paper", "hyuji", "휴지"],
    ["유리", "Glass (material)", "yuri", "유리"],
    ["소금", "Salt", "sogeum", "소금"],
    ["설탕", "Sugar", "seoltang", "설탕"],
    ["감자", "Potato", "gamja", "감자"],
    ["당근", "Carrot", "danggeun", "당근"],
    ["두부", "Tofu", "dubu", "두부"],
    ["김치", "Kimchi", "gimchi", "김치"],
    ["음식", "Food", "eumsik", "음식"],
    ["친구", "Friend", "chingu", "친구"],
    ["가족", "Family", "gajok", "가족"],
    ["학교", "School", "hakgyo", "학교"],
    ["사람", "Person", "saram", "사람"],
    ["사랑", "Love", "sarang", "사랑"],
    ["시간", "Time", "sigan", "시간"],
    ["시장", "Market", "sijang", "시장"],
    ["신문", "Newspaper", "sinmun", "신문"],
    ["사진", "Photo", "sajin", "사진"],
    ["소", "Cow", "so", "소"],
    ["말", "Horse; words or speech", "mal", "말"],
    ["눈", "Eye; snow", "nun", "눈"],
    ["손", "Hand", "son", "손"],
    ["발", "Foot", "bal", "발"],
    ["입", "Mouth", "ip", "입"],
    ["얼굴", "Face", "eolgul", "얼굴"],
    ["옷", "Clothes", "ot", "옷"],
    ["집", "House; home", "jip", "집"],
    ["방", "Room", "bang", "방"],
    ["문", "Door", "mun", "문"],
    ["창문", "Window", "changmun", "창문"],
    ["연필", "Pencil", "yeonpil", "연필"],
    ["공부", "Studying", "gongbu", "공부"],
    ["가방", "Bag", "gabang", "가방"],
    ["강", "River", "gang", "강"],
    ["산", "Mountain", "san", "산"],
    ["섬", "Island", "seom", "섬"],
    ["하늘", "Sky", "haneul", "하늘"],
    ["바람", "Wind", "baram", "바람"],
    ["비", "Rain", "bi", "비"],
    ["봄", "Spring (season)", "bom", "봄"],
    ["여름", "Summer", "yeoreum", "여름"],
    ["가을", "Autumn", "gaeul", "가을"],
    ["겨울", "Winter", "gyeoul", "겨울"],
    ["아침", "Morning; breakfast", "achim", "아침"],
    ["점심", "Lunch", "jeomsim", "점심"],
    ["저녁", "Evening; dinner", "jeonyeok", "저녁"],
    ["오늘", "Today", "oneul", "오늘"],
    ["지금", "Now", "jigeum", "지금"],
    ["이름", "Name", "ireum", "이름"],
    ["한국", "South Korea", "hanguk", "한국"],
    ["한국어", "Korean language", "hangugeo", "한국어"],
    ["운동", "Exercise", "undong", "운동"],
    ["음악", "Music", "eumak", "음악"],
    ["동물", "Animal", "dongmul", "동물"],
    ["물고기", "Fish", "mulgogi", "물고기"],
    ["고양이", "Cat", "goyangi", "고양이"],
    ["강아지", "Puppy; dog", "gangaji", "강아지"],

    // School and campus
    ["학생", "Student", "haksaeng", "학생"],
    ["대학생", "University student", "daehaksaeng", "대학생"],
    ["대학교", "University", "daehakgyo", "대학교"],
    ["전공", "Major; field of study", "jeongong", "전공"],
    ["수업", "Class; lesson", "sueop", "수업"],
    ["강의", "Lecture", "gangui", "강의"],
    ["교수님", "Professor (respectful)", "gyosunim", "교수님"],
    ["선생님", "Teacher (respectful)", "seonsaengnim", "선생님"],
    ["과제", "Assignment", "gwaje", "과제"],
    ["숙제", "Homework", "sukje", "숙제"],
    ["시험", "Exam", "siheom", "시험"],
    ["질문", "Question", "jilmun", "질문"],
    ["교실", "Classroom", "gyosil", "교실"],
    ["도서관", "Library", "doseogwan", "도서관"],
    ["기숙사", "Dormitory", "gisuksa", "기숙사"],
    ["학생증", "Student ID card", "haksaengjeung", "학생증"],
    ["식당", "Restaurant; dining hall", "sikdang", "식당"],
    ["카페", "Café", "kape", "카페"],
    ["화장실", "Restroom", "hwajangsil", "화장실"],
    ["책", "Book", "chaek", "책"],
    ["공책", "Notebook", "gongchaek", "공책"],
    ["노트북", "Laptop", "noteubuk", "노트북"],
    ["컴퓨터", "Computer", "keompyuteo", "컴퓨터"],

    // Clubs, meetings, and music
    ["동아리", "Student club", "dongari", "동아리"],
    ["동아리방", "Club room", "dongaribang", "동아리방"],
    ["모임", "Gathering; meeting", "moim", "모임"],
    ["회원", "Member", "hoewon", "회원"],
    ["신입 회원", "New member", "sinip hoewon", "신입 회원"],
    ["선배", "More senior student or member", "seonbae", "선배"],
    ["후배", "More junior student or member", "hubae", "후배"],
    ["회장", "Club president", "hoejang", "회장"],
    ["회비", "Membership dues", "hoebi", "회비"],
    ["가입", "Joining; membership registration", "gaip", "가입"],
    ["행사", "Event", "haengsa", "행사"],
    ["일정", "Schedule", "iljeong", "일정"],
    ["장소", "Location; venue", "jangso", "장소"],
    ["단체 채팅방", "Group chat", "danche chaetingbang", "단체 채팅방"],
    ["연습", "Practice; rehearsal", "yeonseup", "연습"],
    ["합주", "Playing music together; ensemble rehearsal", "hapju", "합주"],
    ["공연", "Performance; show", "gongyeon", "공연"],
    ["무대", "Stage", "mudae", "무대"],
    ["악보", "Sheet music", "akbo", "악보"],
    ["노래", "Song", "norae", "노래"],
    ["밴드", "Band", "baendeu", "밴드"],
    ["피아노", "Piano", "piano", "피아노"],
    ["기타", "Guitar", "gita", "기타"],
    ["드럼", "Drums", "deureom", "드럼"],
    ["보컬", "Vocals; vocalist", "bokeol", "보컬"],

    // Polite introductions and everyday conversation
    ["안녕하세요.", "Hello. (polite)", "annyeonghaseyo", "안녕하세요."],
    ["반가워요.", "Nice to meet you. (polite)", "bangawoyo", "반가워요."],
    [
      "저는 헨릭이에요.",
      "I’m Henrick. (polite; 헨릭 is a phonetic rendering)",
      "jeoneun henrigieyo",
      "저는 헨릭이에요.",
    ],
    [
      "이름이 뭐예요?",
      "What’s your name? (polite)",
      "ireumi mwoyeyo",
      "이름이 뭐예요?",
    ],
    [
      "저는 대학생이에요.",
      "I’m a university student. (polite)",
      "jeoneun daehaksaengieyo",
      "저는 대학생이에요.",
    ],
    [
      "전공이 뭐예요?",
      "What’s your major? (polite)",
      "jeongongi mwoyeyo",
      "전공이 뭐예요?",
    ],
    [
      "저는 컴퓨터 공학을 공부해요.",
      "I study computer engineering. (polite)",
      "jeoneun keompyuteo gonghageul gongbuhaeyo",
      "저는 컴퓨터 공학을 공부해요.",
    ],
    [
      "한국어를 배우고 있어요.",
      "I’m learning Korean. (polite)",
      "hangugeoreul baeugo isseoyo",
      "한국어를 배우고 있어요.",
    ],
    [
      "한국어를 조금 할 수 있어요.",
      "I can speak a little Korean. (polite)",
      "hangugeoreul jogeum hal su isseoyo",
      "한국어를 조금 할 수 있어요.",
    ],
    [
      "감사합니다.",
      "Thank you. (formal polite)",
      "gamsahamnida",
      "감사합니다.",
    ],
    [
      "고마워요.",
      "Thank you. (conversational polite)",
      "gomawoyo",
      "고마워요.",
    ],
    [
      "죄송합니다.",
      "I’m sorry. (formal polite)",
      "joesonghamnida",
      "죄송합니다.",
    ],
    ["괜찮아요.", "It’s okay; I’m okay. (polite)", "gwaenchanayo", "괜찮아요."],
    ["네.", "Yes. (polite)", "ne", "네."],
    ["아니요.", "No. (polite)", "aniyo", "아니요."],
    ["좋아요.", "Sounds good; I like it. (polite)", "joayo", "좋아요."],
    ["잠시만요.", "One moment, please.", "jamsimanyo", "잠시만요."],
    [
      "다음에 봐요.",
      "See you next time. (polite)",
      "daeume bwayo",
      "다음에 봐요.",
    ],
    [
      "안녕히 가세요.",
      "Goodbye. (polite; to someone leaving)",
      "annyeonghi gaseyo",
      "안녕히 가세요.",
    ],
    [
      "안녕히 계세요.",
      "Goodbye. (polite; to someone staying)",
      "annyeonghi gyeseyo",
      "안녕히 계세요.",
    ],

    // Asking for help with Korean
    [
      "잘 모르겠어요.",
      "I’m not sure; I don’t really know. (polite)",
      "jal moreugesseoyo",
      "잘 모르겠어요.",
    ],
    [
      "이해가 안 돼요.",
      "I don’t understand. (polite)",
      "ihaega an dwaeyo",
      "이해가 안 돼요.",
    ],
    [
      "천천히 말해 주세요.",
      "Please speak slowly.",
      "cheoncheonhi malhae juseyo",
      "천천히 말해 주세요.",
    ],
    [
      "다시 말해 주세요.",
      "Please say it again.",
      "dasi malhae juseyo",
      "다시 말해 주세요.",
    ],
    [
      "이게 무슨 뜻이에요?",
      "What does this mean? (polite)",
      "ige museun tteusieyo",
      "이게 무슨 뜻이에요?",
    ],
    [
      "이거 어떻게 읽어요?",
      "How do you read this? (polite)",
      "igeo eotteoke ilgeoyo",
      "이거 어떻게 읽어요?",
    ],
    [
      "한국어로 뭐라고 해요?",
      "How do you say it in Korean? (polite)",
      "hangugeoro mworago haeyo",
      "한국어로 뭐라고 해요?",
    ],
    ["써 주세요.", "Please write it down.", "sseo juseyo", "써 주세요."],
    [
      "영어로 말해 주세요.",
      "Please say it in English.",
      "yeongeoro malhae juseyo",
      "영어로 말해 주세요.",
    ],
    ["도와주세요.", "Please help me.", "dowajuseyo", "도와주세요."],
    [
      "질문이 있어요.",
      "I have a question. (polite)",
      "jilmuni isseoyo",
      "질문이 있어요.",
    ],

    // Useful at club meetings
    [
      "오늘 처음 왔어요.",
      "This is my first time here. (polite)",
      "oneul cheoeum wasseoyo",
      "오늘 처음 왔어요.",
    ],
    [
      "동아리에 가입하고 싶어요.",
      "I’d like to join the club. (polite)",
      "dongarie gaipago sipeoyo",
      "동아리에 가입하고 싶어요.",
    ],
    [
      "저도 같이 해도 돼요?",
      "May I join in too? (polite)",
      "jeodo gachi haedo dwaeyo",
      "저도 같이 해도 돼요?",
    ],
    [
      "모임은 언제예요?",
      "When is the meeting? (polite)",
      "moimeun eonjeyeyo",
      "모임은 언제예요?",
    ],
    [
      "어디에서 만나요?",
      "Where are we meeting? (polite)",
      "eodieseo mannayo",
      "어디에서 만나요?",
    ],
    [
      "몇 시에 시작해요?",
      "What time does it start? (polite)",
      "myeot sie sijakaeyo",
      "몇 시에 시작해요?",
    ],
    [
      "몇 시에 끝나요?",
      "What time does it end? (polite)",
      "myeot sie kkeunnayo",
      "몇 시에 끝나요?",
    ],
    [
      "여기 앉아도 돼요?",
      "May I sit here? (polite)",
      "yeogi anjado dwaeyo",
      "여기 앉아도 돼요?",
    ],
    [
      "같이 연습해요.",
      "Let’s practice together. (polite)",
      "gachi yeonseupaeyo",
      "같이 연습해요.",
    ],
    [
      "저는 피아노를 쳐요.",
      "I play the piano. (polite)",
      "jeoneun pianoreul chyeoyo",
      "저는 피아노를 쳐요.",
    ],
    [
      "어떤 노래를 좋아해요?",
      "What songs do you like? (polite)",
      "eotteon noraereul joahaeyo",
      "어떤 노래를 좋아해요?",
    ],
    [
      "악보 있어요?",
      "Do you have sheet music? (polite)",
      "akbo isseoyo",
      "악보 있어요?",
    ],
    [
      "처음부터 다시 해요.",
      "Let’s do it again from the beginning. (polite)",
      "cheoeumbuteo dasi haeyo",
      "처음부터 다시 해요.",
    ],
    [
      "조금 천천히 해요.",
      "Let’s do it a little more slowly. (polite)",
      "jogeum cheoncheonhi haeyo",
      "조금 천천히 해요.",
    ],
    [
      "정말 잘했어요!",
      "You did really well! (polite)",
      "jeongmal jalhaesseoyo",
      "정말 잘했어요!",
    ],
    [
      "재미있었어요.",
      "That was fun. (polite)",
      "jaemiisseosseoyo",
      "재미있었어요.",
    ],
    [
      "오늘 수업이 있어요.",
      "I have class today. (polite)",
      "oneul sueobi isseoyo",
      "오늘 수업이 있어요.",
    ],
    [
      "조금 늦을 것 같아요.",
      "I think I’ll be a little late. (polite)",
      "jogeum neujeul geot gatayo",
      "조금 늦을 것 같아요.",
    ],
    [
      "오늘은 못 가요.",
      "I can’t come today. (polite)",
      "oneureun mot gayo",
      "오늘은 못 가요.",
    ],
    [
      "내일 시간 있어요?",
      "Do you have time tomorrow? (polite)",
      "naeil sigan isseoyo",
      "내일 시간 있어요?",
    ],
    [
      "같이 밥 먹을래요?",
      "Would you like to eat together? (conversational polite)",
      "gachi bap meogeullaeyo",
      "같이 밥 먹을래요?",
    ],
    [
      "화장실이 어디예요?",
      "Where is the restroom? (polite)",
      "hwajangsiri eodiyeyo",
      "화장실이 어디예요?",
    ],
  ],
};
export const starterEntries: Entry[] = Object.entries(groups).flatMap(
  ([lessonId, rows]) =>
    rows.map(([front, back, roman, speak], i) => ({
      id: `${lessonId}-${i}`,
      front,
      back,
      roman,
      speak,
      lessonId,
      note: lessonId.includes("consonants")
        ? `Listen to ${speak}, an example syllable (not the letter name).`
        : lessonId.includes("vowels")
          ? `Listen to ${speak}, with a silent initial ㅇ.`
          : "",
    })),
);
